# Generated by Django 6.0.4 on 2026-04-08 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_product_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name_plural": "Products"},
        ),
    ]
